# 1) Install the ComponentType first:
#    kubectl apply -f openchoreo-abstractions/componenttypes/postgres-database.componenttype.yaml
#
# 2) Then apply this example to provision a Postgres DB with persistence.

apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: inventorydatabase
  namespace: default
spec:
  owner:
    projectName: inventorysystem

  # Custom type: <workloadType>/<componentTypeName>
  componentType: statefulset/postgres-database
  autoDeploy: true

  parameters:
    replicas: 1
    port: 5432

    dbName: inventory_db
    dbUser: postgres
    dbPassword: postgres

    storageClassName: local-path
    storageSize: 5Gi

    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    minAvailable: 0

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: inventorydatabase-workload
  namespace: default
spec:
  owner:
    componentName: inventorydatabase
    projectName: inventorysystem
  containers:
    main:
      image: postgres:15-alpine
